### ISSUE TITLE
Year-suffix and original-date are not rendered correctly

### ISSUE THREAD

**Issue by tim-hilde** [bcdavasconcelos/cite-field#2]
Somehow Year-suffix and original-date are not rendered correctly:

```
[@howardWhenceItherTechnology2022]{.year-suffix}  
[@howardWhenceItherTechnology2022]{.original-date}
```

results in 
<img width="160" alt="image" src="https://github.com/bcdavasconcelos/cite-field/assets/44113468/2dca9d25-9ebe-4278-85f4-006267e8d3d8">

This is the bibtex file of the entry:
```
@incollection{howardWhenceItherTechnology2022,
  title = {Whence and {{W}}(h)Ither {{Technology Ethics}}},
  booktitle = {The {{Oxford Handbook}} of {{Philosophy}} of {{Technology}}},
  author = {Howard, Don},
  editor = {Vallor, Shannon},
  year = {2022},
  month = may,
  pages = {78--100},
  publisher = {{Oxford University Press}},
  doi = {10.1093/oxfordhb/9780190851187.013.6},
  urldate = {2023-06-16},
  isbn = {978-0-19-085118-7},
  keywords = {Geschichte der Technikethik,ObsCite,Technikethik,to-review},
  file = {/Users/tim/Documents/Wissensmanagement/Zotero Library/howardWhenceItherTechnology2022.pdf}
}
```

**Comment by bcdavasconcelos** [comment]
What you are seeing is just the citation being rendered without modification by the filter in both cases. You must use the CSL field name, so `.issued` instead of `.year-suffix` should work (see the full documentation [here](https://bcdavasconcelos.github.io/citetools/docs_qmd/03-cite-field.html)). Now, `original-date` won't provide any meaningful result, seeing that the Bibtex reference lacks this information altogether.

**Comment by tim-hilde** [comment]
Thank you so much for your fast reply! I didn't see the more comprehensive documentation you referenced.

**Comment by bcdavasconcelos** [comment]
Not to worry, just let me know if you have any other questions!
